;; Generate dst_table.h by running the command:
;;   sbcl --script dst_table.lisp > pico_w/dst_table.h
;; (Any other Common Lisp implementation should work equally well.)

;; Offset between Common Lisp epoch (1 Jan 1900) and UNIX epoch (1 Jan 1970)
(defvar *epoch* 2208988800)

(defun get-year ()
  (multiple-value-bind
        (s m h d mo yr dow dst-p tz)
      (decode-universal-time (get-universal-time))
    (declare (ignore s m h d mo dow dst-p tz))
    yr))

(defun last-sunday-of-march (year)
  (multiple-value-bind
        (s m h d mo yr dow dst-p tz)
      (decode-universal-time
       (encode-universal-time 0 0 0 31 3 year 0))
    (declare (ignore s m h d mo yr dst-p tz))
    (if (= 6 dow)
        31
        (- 31 1 dow))))

(defun last-sunday-of-october (year)
  (multiple-value-bind
        (s m h d mo yr dow dst-p tz)
      (decode-universal-time
       (encode-universal-time 0 0 0 31 10 year 0))
    (declare (ignore s m h d mo yr dst-p tz))
    (if (= 6 dow)
        31
        (- 31 1 dow))))

(defun dst-transitions (year)
  (values
   (- (encode-universal-time 0 0 1 (last-sunday-of-march year) 3 year 0)
      *epoch*)
   (- (encode-universal-time 0 0 1 (last-sunday-of-october year) 10 year 0)
      *epoch*)))

(defun format-date (ut)
  (multiple-value-bind
        (s m h d mo yr dow dst-p tz)
      (decode-universal-time (+ *epoch* ut))
    (declare (ignore s m h dow dst-p tz))
    (format nil "~4,'0D-~2,'0D-~2,'0D" yr mo d)))

(defun print-dst-table (start-year length)
  (format t "/* generated by dst_table.lisp */~%~%")
  (format t "static int dst_table_start = ~A;~%" start-year)
  (format t "static int dst_table_years = ~A;~%" length)
  (format t "static int dst_table [] =~%{~%")
  (loop for y from start-year below (+ start-year length)
        do (multiple-value-bind
                 (start end)
               (dst-transitions y)
             (format t "   ~A, ~A,  // ~A -- ~A~%"
                     start end (format-date start) (format-date end))))
  (format t "};~%"))

(print-dst-table 2020 80)
